---
title: "Future Shock Scenarios"
author: "Mandy Liesch"
date: "2025-02-20"
output: 
  html_document:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


```

```{r, include=FALSE, eval=FALSE}
rmarkdown::render("ShockScenarios.Rmd", 
                  output_format = "github_document", 
                  output_options = list(toc=TRUE, toc_depth = 4, html_preview=FALSE), 
                  output_file = "README.md")

```

## Load Packages and Files

```{r}
library(tidyverse)

landUse<-read_csv("LandUse_Shocks.csv")

vegShocks<-read_csv("Vegetative_Shocks.csv")
```

### Define color 

```{r}
LUColors <- c("UrbanLand"="#C80813FF", "Tundra"="#71D0F5FF", 
              "Rock/Ice/Desert"="#8A9197FF", "Cropland" = "#FED439FF",
              "HarvCropLand"="#FED439FF", "OtherArableLand" = "#D2AF81FF", 
              "Pasture"= "#FD8CC1FF", "UnmanagedPasture"="#370335FF", 
              "Grassland" = "#46732EFF", "Forest" = "#075149FF", 
              "Shrubland" = "#F05C3BFF", "otherNotArable"="#8A9197FF")

# Vegetative Based Color Pallet
vegCEmissions<-c("#46732EFF")

ModelColors<- c("FAO"="#370335FF", "Houghton" = "#FED439FF", 
                "GCAM" = "#FED439FF", "HWSD"="#1A9993FF", "SG17" = "#197EC0FF",
                "SG20"="#F05C3BFF")


```

# Land Use 

```{r}
#Break up the land leaf columns into subsets 
#(each land leaf has 4 different categories)
new_LU<-landUse %>% 
  separate(LandLeaf, c("LandUse", "Basin", "Water", "Input")) %>%
  separate(scenario, into = c('scenario', 'date'), sep = ",") %>%
  select(-c("date", "Basin", "Units"))


#Sum together all of the land leaf files by land use type
sum_new_LU<- new_LU %>% 
  group_by(scenario, LandUse) %>% 
  summarise(across(where(is.numeric), sum))

#Reclassify land use types into broader categories
cat_LU<-sum_new_LU %>% 
  mutate(Category = case_when(
  #Cropland category  
  LandUse %in% 
    #Biomass Crops
    c("biomassGrass", "biomassTree",  
    #Fodder Crops
      "FodderGrass", "FodderHerb", 
    #Grain Crops
      "Corn",  "Soybean", "Wheat", "OtherGrain",
    #Oil Crops
      "OilCrop", "Rapeseed", 
    #Other Crops
      "FiberCrop", "MiscCrop", "RootTuber",  "SugarCrop") 
    #Land Use Name
      ~ "HarvCropLand",
    #Other Arable Land
    LandUse == "OtherArableLand" ~"OtherArableLand",
    #Forest categories
    LandUse %in% c("Forest", "UnmanagedForest", "ProtectedUnmanagedForest")
                ~ "Forest",
    #Grassland categories
    LandUse %in% c("Grassland", "ProtectedGrassland") ~ "Grassland", 
    #Pasture category
    LandUse=="Pasture" ~ "Pasture",
    #Unamanged pasture category
    LandUse %in% c("ProtectedUnmanagedPasture", "UnmanagedPasture") 
              ~ "UnmanagedPasture",
    #Shrubland category
    LandUse %in% c("Shrubland", "ProtectedShrubland") ~ "Shrubland",
    #Other categories
    LandUse=="Tundra" ~ "Tundra",
    LandUse=="UrbanLand" ~ "UrbanLand",
    #Default Return Statement
    TRUE~NA_character_
  )
)

#Sum everything up by defined land use category
sum_cat_LU<-cat_LU %>% 
  group_by(scenario, Category) %>% 
  summarise(across(where(is.numeric), sum))

#Create a long dataframe with land use, years, and area 
wide_sum_LU<-sum_cat_LU %>% 
  pivot_longer(!c(scenario, Category), names_to=c("year"), values_to = "area") %>%
  #convert years into the numeric values
  mutate(year = as.numeric(year)) %>% 
  pivot_wider(names_from = scenario, values_from = c(area)) %>%
  mutate(DifCornShock = CORN1BG - BASE) %>%
  mutate(DifSoyShock = SOY1BG - BASE) %>%
  group_by(Category) %>%
  mutate(CumSumCornLand = cumsum(DifCornShock)) %>%
  mutate(CumSumSoyLand = cumsum(DifSoyShock))
  
  
```

## Shock Scenario Land Use Plots

```{r}
#Create a spaghetti plot of land use area using area by category
CornShockLandUseLines.plt<-ggplot(data= wide_sum_LU %>%
                                    filter(year >2020), 
                         aes(x=year, y=DifCornShock, fill=Category, group=Category))+
  geom_bar(position="stack", stat="identity") +
  
  #geom_line(aes(color=Category), size=2) +
  #add a title
  ggtitle("Corn Shock Land Use Change Over Baseline by Land Use Type") +
  #add labels
  labs( x='Year', y='Land Area (thous sq km)') +
  #use the custom color pallette
  scale_fill_manual(values=LUColors, name = "Land Use", 
                     labels = c( "Forest", "Grassland", "Harvested Cropland", 
                                 "Other Arable Land", "Pasture", "Shrubland", 
                                 "Tundra", "Unmanaged Pasture", "Urban Land"))


#Create a spaghetti plot of land use area using area by category
SoyShockLandUseLines.plt<-ggplot(data= wide_sum_LU %>%
                                    filter(year >2020),
                         aes(x=year, y=DifSoyShock, fill=Category, group=Category))+
  geom_bar(position="stack", stat="identity") +
  #add a title
  ggtitle("Soy Shock Land Use Change Over Baseline by Land Use Type") +
  #add labels
  labs( x='Year', y='Land Area (thous sq km)') +
  #use the custom color pallette
  scale_fill_manual(values=LUColors, name = "Land Use", 
                     labels = c( "Forest", "Grassland", "Harvested Cropland", 
                                 "Other Arable Land", "Pasture", "Shrubland", 
                                 "Tundra", "Unmanaged Pasture", "Urban Land"))

CumCornShockLandUseLines.plt<-ggplot(data= wide_sum_LU %>%
                                    filter(year >2020), 
                         aes(x=year, y=CumSumCornLand, fill=Category, group=Category))+
  geom_bar(position="stack", stat="identity") +
  #add a title
  #ggtitle("Corn Shock Land Use Change Over Baseline by Land Use Type") +
  #add labels
  labs( x='Year', y='Land Area (thous sq km)') +
  #use the custom color pallette
  scale_fill_manual(values=LUColors, name = "Land Use", 
                     labels = c( "Forest", "Grassland", "Harvested Cropland", 
                                 "Other Arable Land", "Pasture", "Shrubland", 
                                 "Tundra", "Unmanaged Pasture", "Urban Land"))

CumSoyShockLandUseLines.plt<-ggplot(data= wide_sum_LU %>%
                                    filter(year >2020), 
                         aes(x=year, y=CumSumSoyLand, fill=Category, group=Category))+
  geom_bar(position="stack", stat="identity") +
  #add a title
  #ggtitle("Corn Shock Land Use Change Over Baseline by Land Use Type") +
  #add labels
  labs( x='Year', y='Land Area (thous sq km)') +
  #use the custom color pallette
  scale_fill_manual(values=LUColors, name = "Land Use", 
                     labels = c( "Forest", "Grassland", "Harvested Cropland", 
                                 "Other Arable Land", "Pasture", "Shrubland", 
                                 "Tundra", "Unmanaged Pasture", "Urban Land"))
```

# Vegetative Data

```{r}
#Break up the land leaf columns into subsets 
#(each land leaf has 4 different categories)
new_veg<-vegShocks %>% 
  separate(LandLeaf, c("LandUse", "Basin", "Water", "Input")) %>%
  separate(scenario, into = c('scenario', 'date'), sep = ",") %>%
  select(-c("date", "Basin", "Units"))


#Sum together all of the land leaf files by land use type
sum_new_veg<- new_veg %>% 
  group_by(scenario, LandUse) %>% 
  summarise(across(where(is.numeric), sum))

#Reclassify land use types into broader categories
cat_veg<-sum_new_veg %>% 
  mutate(Category = case_when(
  #Cropland category  
  LandUse %in% 
    #Biomass Crops
    c("biomassGrass", "biomassTree",  
    #Fodder Crops
      "FodderGrass", "FodderHerb", 
    #Grain Crops
      "Corn",  "Soybean", "Wheat", "OtherGrain",
    #Oil Crops
      "OilCrop", "Rapeseed", 
    #Other Crops
      "FiberCrop", "MiscCrop", "RootTuber",  "SugarCrop") 
    #Land Use Name
      ~ "HarvCropLand",
    #Other Arable Land
    LandUse == "OtherArableLand" ~"OtherArableLand",
    #Forest categories
    LandUse %in% c("Forest", "UnmanagedForest", "ProtectedUnmanagedForest")
                ~ "Forest",
    #Grassland categories
    LandUse %in% c("Grassland", "ProtectedGrassland") ~ "Grassland", 
    #Pasture category
    LandUse=="Pasture" ~ "Pasture",
    #Unamanged pasture category
    LandUse %in% c("ProtectedUnmanagedPasture", "UnmanagedPasture") 
              ~ "UnmanagedPasture",
    #Shrubland category
    LandUse %in% c("Shrubland", "ProtectedShrubland") ~ "Shrubland",
    #Other categories
    LandUse=="Tundra" ~ "Tundra",
    LandUse=="UrbanLand" ~ "UrbanLand",
    #Default Return Statement
    TRUE~NA_character_
  )
)

#Sum everything up by defined land use category
sum_cat_veg<-cat_veg %>% 
  group_by(scenario, Category) %>% 
  summarise(across(where(is.numeric), sum)) %>%
  select(scenario:'2060')


#Create a long dataframe with land use, years, and area 
wide_sum_veg<-sum_cat_veg  %>% 
  pivot_longer(!c(scenario, Category), names_to=c("year"), values_to = "area") %>%
  #convert years into the numeric values
  mutate(year = as.numeric(year)) %>% 
  pivot_wider(names_from = scenario, values_from = c(area)) %>%
  mutate(DifCornShock = CORN1BG - BASE) %>%
  mutate(DifSoyShock = SOY1BG - BASE) %>%
  group_by(Category) %>%
  mutate(cumSumCornVeg= cumsum(DifCornShock))%>%
  mutate(cumSumSoyVeg= cumsum(DifSoyShock))


```

## Vegetative Graphs

```{r}
#Create a spaghetti plot of land use area using area by category
CSSS_ShockVegLines.plt<-ggplot(data= wide_sum_veg %>%
                                    filter(year >2015)) +
  geom_line(aes(x=year, y=DifCornShock, color=Category, linetype = "Corn"), size=2) +
  geom_line(aes(x=year, y=DifSoyShock, color=Category, linetype = "Soy"), size=2) +
  #add a title
  ggtitle("Corn and Soy Shock Vegetative Emission Change Over Baseline by Land Use Type") +
  #add labels
  labs( x='Year', y='Vegetative Emissions (Mt)', linetype="Shock Type") +
  #use the custom color pallette
  scale_color_manual(values=LUColors, name = "Land Use", 
                     labels = c( "Forest", "Grassland", "Harvested Cropland", 
                                 "Other Arable Land", "Pasture", "Shrubland", 
                                 "Tundra", "Unmanaged Pasture", "Urban Land"))


#Create a spaghetti plot of land use area using area by category
cum_CSSS_VegLines.plt<-ggplot(data= wide_sum_veg %>%
                                    filter(year >2015)) +
  geom_line(aes(x=year, y=cumSumCornVeg, color=Category, linetype="Corn"), size=2) +
  geom_line(aes(x=year, y=cumSumSoyVeg, color=Category, linetype="Soy"), size=2) +
  #add a title
  ggtitle("Corn and Soy Shock Cumulative Vegetative Emission Change Over Baseline by Land Use Type") +
  #add labels
  labs( x='Year', y='Vegetative Emissions (Mt)', linetype="Shock Type") +
  #use the custom color pallette
  scale_color_manual(values=LUColors, name = "Land Use", 
                     labels = c( "Forest", "Grassland", "Harvested Cropland", 
                                 "Other Arable Land", "Pasture", "Shrubland", 
                                 "Tundra", "Unmanaged Pasture", "Urban Land"))



```

## Soils Data

```{r}
#Create a series loop to read in all of the data

#Create a list of all .csv files in the output folder
files <- list.files(path="Shocks", pattern = "\\values.csv$", 
                    full.names = TRUE)

#Initialize an empty list to store data frames
data_list <- list()

# Loop over each file and read it into a data frame
for (file in files) {
  data <- read.csv(file)
  data_list[[file]] <- data
}

# Combine all data frames into one
combined_shock_soil_data <- bind_rows(data_list)

new_Soil_Shock_Emiss<- combined_shock_soil_data %>% 
  separate(LandLeaf, c("LandUse", "Basin", "Water", "Input")) %>%
  separate(scenario, into = c('scenario', 'date'), sep = ",") %>%
  select(-c("date", "region", "Basin", "Units"))  %>%
  select(Series:'X2060')

#Sum together all of the land leaf files by land use type
sum_new_Soil_Emiss<- new_Soil_Shock_Emiss %>% 
  group_by(Series, scenario, LandUse) %>% 
  summarise(across(where(is.numeric), sum))

#Reclassify land use types into broader categories
cat_Soil_Emiss<-sum_new_Soil_Emiss %>% 
  mutate(Category = case_when(
  #Cropland category  
  LandUse %in% 
    #Biomass Crops
    c("biomassGrass", "biomassTree",  
    #Fodder Crops
      "FodderGrass", "FodderHerb", 
    #Grain Crops
      "Corn",  "Soybean", "Wheat", "OtherGrain",
    #Oil Crops
      "OilCrop", "Rapeseed", 
    #Other Crops
      "FiberCrop", "MiscCrop", "RootTuber",  "SugarCrop") 
    #Land Use Name
      ~ "HarvCropLand",
    #Other Arable Land
    LandUse == "OtherArableLand" ~"OtherArableLand",
    #Forest categories
    LandUse %in% c("Forest", "UnmanagedForest", "ProtectedUnmanagedForest")
                ~ "Forest",
    #Grassland categories
    LandUse %in% c("Grassland", "ProtectedGrassland") ~ "Grassland", 
    #Pasture category
    LandUse=="Pasture" ~ "Pasture",
    #Unamanged pasture category
    LandUse %in% c("ProtectedUnmanagedPasture", "UnmanagedPasture") 
              ~ "UnmanagedPasture",
    #Shrubland category
    LandUse %in% c("Shrubland", "ProtectedShrubland") ~ "Shrubland",
    #Other categories
    LandUse=="Tundra" ~ "Tundra",
    LandUse=="UrbanLand" ~ "UrbanLand",
    #Default Return Statement
    TRUE~NA_character_
  )
)

#Sum everything up by defined land use category
sum_cat_soil_emiss<- cat_Soil_Emiss %>% 
  group_by(Series, scenario, Category) %>% 
  summarise(across(where(is.numeric), sum))

#Create a long dataframe with land use, years, and area 
wide_sum_soil_emiss<- sum_cat_soil_emiss %>% 
  pivot_longer(!c(Series, scenario, Category), names_to=c("year"), values_to = "area") %>%
  #Remove the extra X value from the dataset
  mutate(across(c('year'), substr, 2, nchar(year))) %>%
  #convert years into the numeric values
  mutate(year = as.numeric(year)) %>% 
  pivot_wider(names_from = scenario, values_from = c(area)) %>%
  mutate(DifCornShock = CORN1BG - BASE) %>%
  mutate(DifSoyShock = SOY1BG - BASE)

cum_soil_emiss_sums<-wide_sum_soil_emiss %>%
   group_by(Series, year) %>% 
  summarise(across(where(is.numeric), sum)) %>%
#calculate the cumulative emissions
  mutate(aggDifCorncount = cumsum(DifCornShock)) %>%
  mutate(aggDifSoycount = cumsum(DifSoyShock))
  

```


## Net Emissions

```{r}
mergedData<-merge(wide_sum_soil_emiss, wide_sum_veg, 
                  by=c("Category", "year"), all=TRUE) %>%
#rename all of the columns after the merge
               rename( c( "BASE.soil" ="BASE.x", 
                           "BASE.veg" = "BASE.y", 
                           "CORN1BG.soil" =  "CORN1BG.x", 
                           "CORN1BG.veg" = "CORN1BG.y",
                          "SOY1BG.soil" =  "SOY1BG.x", 
                           "SOY1BG.veg" = "SOY1BG.y",
                          "DifCornShock.soil" = "DifCornShock.x", 
                          "DifSoyShock.soil" = "DifSoyShock.x", 
                           "DifCornShock.veg" = "DifCornShock.y", 
                          "DifSoyShock.veg" = "DifSoyShock.y" )) %>%
                dplyr::mutate(netDifCornShock = DifCornShock.soil + DifCornShock.veg) %>%
                dplyr::mutate(netDifSoyShock = DifSoyShock.soil + DifSoyShock.veg)

sum_merged_data <- mergedData %>%
   group_by(Series, year) %>% 
  dplyr::summarise(across(where(is.numeric), sum)) %>%
  group_by(Series) %>%
  dplyr::mutate(aggNetSumDifCorncount = cumsum(netDifCornShock)) %>%
  dplyr::mutate(aggNetSumDifSoycount = cumsum(netDifSoyShock))


#sum_merged_data$aggNetSumDifCorncount <- ave(sum_merged_data$netDifCornShock, sum_merged_data$Series, FUN=cumsum)

#sum_merged_data$aggNetSumDifSoycount <- ave(sum_merged_data$netDifSoyShock, sum_merged_data$Series, FUN=cumsum)

net_emiss_CSSS_Models.plt<-ggplot(data= sum_merged_data  %>%
                                    filter(year > 2015)) +
  geom_line(aes(x=year, y=netDifCornShock, color=Series, linetype="Corn"), size=2) +
  geom_line(aes(x=year, y=netDifSoyShock, color=Series, linetype="Soy"), size=2) +
  #add a title
  ggtitle("Total Net Corn and Soy Shock Emissions Over Baseline") +
  #add labels
  labs( x='Year', y='Emissions (Mt)', linetype="Shock Type") +
  #use the custom color pallette
  scale_color_manual(values=ModelColors)


cum_net_emiss_CSSS_Models.plt<-ggplot(data= sum_merged_data %>%
                                    filter(year > 2015)) + 
  geom_line(aes(x=year, y=aggNetSumDifCorncount, color=Series, linetype = "Corn"), size=2) +
  geom_line(aes(x=year, y=aggNetSumDifSoycount, color=Series, linetype= "Soy"), size=2) +
  #add a title
  ggtitle("Total Net Cumulative Corn and Soy Shock Emissions Over Baseline") +
  #add labels
  labs( x='Year', y='Emissions (Mt)', linetype="Shock Type") +
  #use the custom color pallette
  scale_color_manual(values=ModelColors)



```


## Soil Emissions

```{r}
cum_soil_emiss_sums_CSSS_Models.plt<-ggplot(data= cum_soil_emiss_sums %>%
                                    filter(year > 2015)) +
  geom_line(aes(x=year, y=DifCornShock, color=Series,linetype = "Corn"), size=2) +
  geom_line(aes(x=year, y=DifSoyShock, color=Series, linetype="Soy"), size=2) +
  #add a title
  ggtitle("Total Corn and Soy Shock Emissions Over Baseline") +
  #add labels
  labs( x='Year', y='Emissions (Mt)', linetype="Shock Type") +
  #use the custom color pallette
  scale_color_manual(values=ModelColors) 
  
      

tot_cum_soil_emiss_sums_CSSS_Models.plt<-ggplot(data= cum_soil_emiss_sums %>%
                                    filter(year > 2015)) + 
  geom_line(aes(x=year, y=aggDifCorncount, color=Series, linetype= "Corn"), size=2) +
  geom_line(aes(x=year, y=aggDifSoycount, color=Series, linetype="Soy"), size=2) +
  #add a title
  ggtitle("Soil Cumulative Corn and Soy Shock Emissions Over Baseline") +
  #add labels
  labs( x='Year', y='Emissions (Mt)') +
  #use the custom color pallette
  scale_color_manual(values=ModelColors)




```


```{r}

unmanPast_soil_emiss_sums_CS_Models.plt<-ggplot(data= wide_sum_soil_emiss %>%
                                    filter(Category == "UnmanagedPasture"), 
                         aes(x=year, y=DifCornShock, group=Series))+
  geom_line(aes(color=Series), size=2) +
  #add a title
  ggtitle("Unmanaged Pasture Corn Shock Emissions Over Baseline") +
  #add labels
  labs( x='Year', y='Emissions (Mt)') +
  #use the custom color pallette
  scale_color_manual(values=ModelColors)


unmanPast_soil_emiss_sums_SS_Models.plt<-ggplot(data= wide_sum_soil_emiss %>%
                                    filter(Category == "UnmanagedPasture"), 
                         aes(x=year, y=DifSoyShock, group=Series))+
  geom_line(aes(color=Series), size=2) +
  #add a title
  ggtitle("Unmanaged Pasture Soy Shock Emissions Over Baseline") +
  #add labels
  labs( x='Year', y='Emissions (Mt)') +
  #use the custom color pallette
  scale_color_manual(values=ModelColors)

```

```{r}

```